@startmindmap
*_ <b>РИСКИ И ДОЛГИ </b>
**[#FFBBCC] <u>Риски</u>
***[#FFBBCC] Недоступность внешних систем
***[#FFBBCC] Высокая нагрузка
***[#FFBBCC] Уязвимости в свободном ПО
***[#FFBBCC] Разрастание пакетов с кодом
**[#yellow] Долги
***[#yellow] Сбор и хранение логов (ElasticSearch)
***[#yellow] Компенсационные сценарии (Ошибки оплаты, доставки, наличия товара ит.д.)
***[#yellow] Управление транзакциями в случае ошибок в сервисах (Service Mesh)

@endmindmap